services:
  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: expense-db
    restart: always
    environment:
      MYSQL_DATABASE: 'expense_manager_db'
      # MYSQL_USER: 'user'
      # MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3307:3306" # Expõe a porta para o host (opcional, bom para debug)
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Serviço da Aplicação (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-app
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # Serviço do Servidor Web (Nginx)
  webserver:
    image: nginx:alpine
    container_name: expense-webserver
    restart: always
    ports:
      - "8080:80" # Acessaremos a API em http://localhost:8080
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local